### ISSUE TITLE
Create the end point for get all CalendarEvents

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm-node-api#30]
Create the Prospects end point to get all the data

- The end point should be GET /calendarevents
- Should check for the module permission and the view action permitted or not
- The field should be added for attributes are
```
event_type    
subject       
description   
location      
priority      
start_date    
start_time    
end_date      
end_time      
event_status  
assigned_to   
added_on      
last_modified 
idevents      
related_to    
events_reminder
```
- The `related_to` will have the following attributes
```
module_name
moduleId
related_to_id
related_to_value
```
- The `events_reminder` will have the following attributes
```
days
hours
minutes
email_ids
reminder_send - boolean
```
- We will not add custom fields for now.
- Should follow the JSONAPI standard
- Attributes should be camel case.
- Should support pagination

**Comment by abhikchakraborty** [comment]
The end point is ready and here is the PR https://github.com/sQcrm/sqcrm-node-api/pull/33
