### ISSUE TITLE
Create the end point for get all Vendors

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm-node-api#34]
Create the Vendors end point to get all the data

- The end point should be `GET /vendors`
- Should check for the module permission and the view action permitted or not
- The field should be added for attributes are
```
 vendor_name    
 email              
 phone             
 website           
 description        
 assigned_to        
 added_on           
 last_modified      
 address
```
- The `address` attribute will be an object with its own attribute as
```
vendor_street     
vendor_city       
vendor_postal_code 
vendor_po_box      
vendor_state       
vendor_country     
```
- We will not add custom fields for now.
- Should follow the JSONAPI standard
- Attributes should be camel case.
- Should support pagination

**Comment by abhikchakraborty** [comment]
The end point is ready and here is the PR https://github.com/sQcrm/sqcrm-node-api/pull/35
