### ISSUE TITLE
Create the end point for get all Products

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm-node-api#37]
Create the Products end point to get all the data

- The end point should be `GET /products`
- Should check for the module permission and the view action permitted or not
- The field should be added for attributes are
```
 product_name   
 is_active          
 product_category   
 manufacturer       
 idvendor           
 vendor_name
 website            
 description        
 assigned_to        
 added_on           
 last_modified     
 price_information            
 quantity
 tax_value         
```
- The `tax_value` is returned from the table `products_tax` and the query to get the data is https://github.com/sQcrm/sqcrm/blob/master/modules/Products/Products.class.php#L68

**NOTE**
Need to make sure that the query is using `group by idproducts`

The tax value via the query will be returned something as
`VAT::12.000,Sales::4.000`
 
- Now the `tax_value` will have the following attributes
```
tax_name
tax_value
```
- Since these values are grouped and data is retrieved as `VAT::12.000,Sales::4.000` the `tax_value` values needs to be formatted as
```
"taxValue" [
 {
   "taxName" : "VAT",
   "taxValue" : "12.000"
 },
 {
   "taxName" : "Sales",
   "taxValue" : "4.000"
 },
]
```
- The `quantity` should be returned as object and the attributes are as
```
unit_quantity      
quantity_in_stock  
quantity_in_demand 
```
- The `price_information` should be returned as object and the attributes are as
```
product_price      
commission_rate  
```
- We will not add custom fields for now.
- Should follow the JSONAPI standard
- Attributes should be camel case.
- Should support pagination

**Comment by vivekshekar** [comment]
@abhikchakraborty 

This is done, 
Please check here is the merge request, 

https://github.com/sQcrm/sqcrm-node-api/pull/40
