### ISSUE TITLE
Product taxValue formatting

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm-node-api#41]
In the products end point we would now need to format the attribute `tax_value` to return the data as
```
"taxValue" [
 {
   "taxName" : "VAT",
   "taxValue" : "12.000"
 },
 {
   "taxName" : "Sales",
   "taxValue" : "4.000"
 },
]
```

This is already done for the `quotes` end point and the function to parse the data is available on https://github.com/sQcrm/sqcrm-node-api/blob/develop/utils/common.js#L9

**Comment by sQcrm** [comment]
@vivekshekar any update ?

**Comment by vivekshekar** [comment]
@abhikchakraborty 

Yes this is done, 
here is the merge request,

https://github.com/sQcrm/sqcrm-node-api/pull/48
