### ISSUE TITLE
Bug fixes

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm-node-api#46]
There are some minor bug fixes that needs to be taken care

- https://github.com/sQcrm/sqcrm-node-api/blob/develop/controllers/salesorder.js#L85

Wrong comment for the function

- https://github.com/sQcrm/sqcrm-node-api/blob/develop/controllers/salesorder.js#L159

Function name should be changed to `setTaxAndSONumValues`

- https://github.com/sQcrm/sqcrm-node-api/blob/develop/controllers/salesorder.js#L174

Wrong comment for the function

- https://github.com/sQcrm/sqcrm-node-api/blob/develop/controllers/quotes.js#L155

Wrong function name and comment and the function name should be `setTaxAndQuoteNumValues`

**Comment by abhikchakraborty** [comment]
Here is the PR for the fixes https://github.com/sQcrm/sqcrm-node-api/pull/47
